name: flutter_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  markdown: ^2.1.1
  meta: ^1.0.5
  string_scanner: ^1.0.0
  path: ^1.5.1
  flutter_svg: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.9-pre.94 <2.0.0"

flutter:
  assets:
    - assets/logo.png
